---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openstack-ingress-controller
  namespace: kube-system
# ---
# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: openstack-ingress-controller
# rules:
#   - apiGroups: [""]
#     resources: ["ResourceAll"]
#     verbs: ["VerbAll"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openstack-ingress-controller-binding
subjects:
  - kind: ServiceAccount
    name: openstack-ingress-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
